[build]
  base    = "projects/whatchucookin/backend/whatchucookin-frontend"
  publish = "dist"
  command = "npm ci && npm run build"


[build.environment]
    VITE_API_BASE= "https://api.killstzy.com"